name: .NET Core API Build

on:
  push:
    branches: [ "master", "features/Repositories" ] # Added your feature branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # Use Linux for web apps, it's faster and cheaper

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # This is the correct action for checking out code

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x 

    - name: Restore dependencies
      # Use the correct solution name from your screenshot
      run: dotnet restore AgendamentosTo.sln

    - name: Build
      # Use the correct solution name
      run: dotnet build AgendamentosTo.sln --no-restore --configuration Release


    # - name: Test
    #   run: dotnet test --no-build --configuration Release
